
github: # MMONSTER124
[https://github.com/MMONSTER124]

"account index": 2592906,
"AccountIdHash": "0fa4571185a72f98ae7fe6f3ba1dafe4c40c495e89e4f4ed951d3d14725e86f2",
"TotalEquity": 4287399285800000,
"TotalDebt": 3442722385200000,
"Assets" : [ {
"Index": 2,
"Networth": 4053,
"Debt": 19
}, {
"Index": 148,
"Networth": 3127886,
"Debt": 2587484
} ],
 "Root": "272cafea86240006f4e0d08502ff06d55e386202a48c38eab98304f43ec54266",
"Proof": [ "LhX8NdPxmmsN0UeMOLB0C9bcSrDaVslrk7+/wayVF44=", "GoLC22vcDMvA1kMBjNAX60BT4QmE7kmgKK++IAfFIvk=", "KAFtSjKxg5juRnfJE13Fm7nU1WUM0rYFiPO8+PBghbc=", "EvwIHunWHt/pfLTpcU0dlHofuGeZZHXgrUA8GUESYdo=",  "HKKL1Tab0UrVpBD68iK1mbik9Pw/lfn5ioMghESnn8M=", "HxP4gI08JxaJibvZEL30xuX5aiqdUO22Gt6QsxegAQs=", "GYTtdi/ONE27BIqHf2aCH2rcndbSI9tPUfLkdABdz0w=", 8VfTOibf3wshposQVz6nzfKhzU1WO3o6uQ=", "BxQZwRrGGrLMII4Gm5/SdVesithff9PwmIre94zcwnI=", "A9vNlxt4LbqD ctidGqpm+/faP/FR6S/fUjc91RaaFKo=",  "H8QC7vvqtQWg4yrYMEQ9uwTMBIDjwY0rTnqyrcMM4H4=", "G3Dg/V4C+sGqZiQXv55DhXlcQgJgOpijvoRu8CbqbgI=", "LqnwEFVP971Mt4PUmbBMAcyhX0AqmY3RH+z5GdPOJdA=", " KLdjD1hGTxKWhcvpd/KxULKf9TXE7fvyw5Hq/IIgasM=", "JU5QaEwXPf5YiSRpKLtwG1QcJmxOFAwh4wrbR4sFvDs=", jSzyOQdyX1Yg3c86JvkHx6bSh6z15fp5pepPeUyA=",  "EHfdjjbtd9d7bjhyUpoJXWmvHQm9RYpvFSEHjtJHLJk=", "I8m1IIQRcCrjxEGYeLbGTBZhp5cj+uQyKrS129i6AIw=", "I7hMJCzWsvgx7J7zQdlRRX7KOZU25bVyaInGX064Bg 8=,”  "EARemVtcpq9NGIcasaFYLZhAd2+rd9p2klWxizrY7ig=", "IWPO/Hp1trxgbsfkab8tD9JGyjRBUuXgKl0SUhW4qtY=", "Ka9Bm2US+/WINDk8MvytsX20bHmJZNoGWbwHD4VEUdc=", "DQaCV6xirXclfSEXLz5CThuLajuIKgG47BeV0u6jHHs=", "G3j3tGx68tGwEASTdGp53FVLiVKbv9e6NAYoXXX919M=", "FZccOkiNSW8NLDCniDlhv5iB8nemSPBCGmovBe5UdBc=" ]
}